services:
    api:
        image: shabel/profile-management
        env_file:
            - .env
        ports:
            - 8000:8000
        restart: always
        command: bash -c "
            alembic upgrade head &&
            uvicorn src.main:app --host 0.0.0.0 --port 8000
            "
