services:
    api:
        build: .
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
#         depends_on:
#             - db

#     db:
#         image: postgres
#         restart: always
#         volumes:
#             - /.pgdata-pm:/var/lib/postgresql/data
#         env_file:
#             - .env
#         environment:
#             - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#             - POSTGRES_DB=${POSTGRES_DB}

# volumes:
#     .pgdata-pm:
