name: Build and Deploy

on:
    push:
        branches:
            - main
            - production
    pull_request:
        branches:
            - production

jobs:
    build:
        runs-on: ubuntu-latest

        environment:
            name: production
        env:
            DATABASE_URL: ${{secrets.DATABASE_URL}}
            SQL_ALCHEMY_URL: ${{secrets.SQL_ALCHEMY_URL}}
            JWT_SECRET: ${{secrets.JWT_SECRET}}
            JWT_ACCESS_TOKEN_EXPIRES_MINUTES: ${{secrets.JWT_ACCESS_TOKEN_EXPIRES_MINUTES}}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install PIP
              run: python -m pip install --upgrade pip
            - name: Install all Dependencies
              run: pip install -r requirements.txt

    deploy:
        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install SSH
              run: sudo apt-get install openssh-client
