name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repository
              uses: actions/checkout@v2
            - name: build triggering...
              run: echo "triggering build now..."
