name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - production

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # login to dockerhub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            # enhance image building performance
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/profile-management:latest
                  # cache image layers to optimize performance
                  cache-from: type=ga
                  cache-to: type=gha, mode=max

    deploy:
        runs-on: ubuntu-latest
        environment: production
